project:
  type: website
  output-dir: docs

website:
  title: "Jessica Kristin Reese"
  navbar:
    left:
      - href: index.qmd
        text: "Home"      
      - href: research.qmd
        text: "Research"
      - href: data.qmd
        text: "Data"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

