project:
  type: website
  output-dir: docs

website:
  title: "Jessica Kristin Reese"
  navbar:
    left:
      - href: index.qmd
        text: "Home"      
      - href: research.qmd
        text: "Research"
      - href: https://gvpt.umd.edu/sites/gvpt.umd.edu/files/cv/CV%20-%20Jessica%20Reese.pdf

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

