project:
  type: website
  output-dir: docs

website:
  title: "Jessica Kristin Reese"
  navbar:
    left:
      - href: index.qmd
        text: "Home"      
      - href: about.qmd
        text: "About"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

